documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**

platform/frontend:
  - changed-files:
      - any-glob-to-any-file: autogpt_platform/frontend/**

platform/backend:
  - changed-files:
      - all-globs-to-any-file:
          - autogpt_platform/backend/**
          - "!autogpt_platform/backend/backend/blocks/**"

platform/blocks:
  - changed-files:
      - any-glob-to-any-file: autogpt_platform/backend/backend/blocks/**
