name: 'Run Prisma Migrations'
description: 'Sets up Python and runs Prisma migrations for AutoGPT Platform backend'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  database-url:
    description: 'Database URL connection string'
    required: true
  git-ref:
    description: 'Git ref to checkout (branch/tag/commit)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.git-ref || github.ref_name }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install Prisma dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install prisma

    - name: Run Prisma migrations
      shell: bash
      working-directory: ./autogpt_platform/backend
      run: python -m prisma migrate deploy
      env:
        DATABASE_URL: ${{ inputs.database-url }}
        DIRECT_URL: ${{ inputs.database-url }}
