name: "Run Prisma Migrations"
description: "Sets up environment via mise and runs Prisma migrations for AutoGPT Platform backend"
inputs:
  python-version:
    description: "Python version to use (overrides mise.toml default)"
    required: false
    default: ""
  database-url:
    description: "Database URL connection string"
    required: true
  git-ref:
    description: "Git ref to checkout (branch/tag/commit)"
    required: false
    default: ""
  mise-version:
    description: "Mise version to use"
    required: false
    default: "2026.1.10"
  generate-client:
    description: "Whether to run prisma generate after migrations"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.git-ref || github.ref_name }}

    - name: Setup mise
      uses: jdx/mise-action@v3
      with:
        version: ${{ inputs.mise-version }}
        install: true
        cache: true
        cache_key_prefix: mise-prisma
        working_directory: autogpt_platform
        github_token: ${{ github.token }}
        log_level: info
        install_args: ${{ inputs.python-version && format('python@{0}', inputs.python-version) || '' }}

    - name: Install backend dependencies
      shell: bash
      working-directory: ./autogpt_platform/backend
      run: poetry install --only main --no-interaction

    - name: Run Prisma migrations
      shell: bash
      working-directory: ./autogpt_platform/backend
      run: poetry run prisma migrate deploy
      env:
        DATABASE_URL: ${{ inputs.database-url }}
        DIRECT_URL: ${{ inputs.database-url }}

    - name: Generate Prisma client
      if: ${{ inputs.generate-client == 'true' }}
      shell: bash
      working-directory: ./autogpt_platform/backend
      run: poetry run prisma generate
      env:
        DATABASE_URL: ${{ inputs.database-url }}
        DIRECT_URL: ${{ inputs.database-url }}
